# ============================================
# Multi-stage build for Dropfast - Production Ready
# Optimized for minimal image size (~300MB vs 1GB+)
# ============================================
# syntax=docker/dockerfile:1.4

# ============================================
# Stage 1: Base image with dependencies
# ============================================
FROM node:18-alpine AS base

# Install OpenSSL (required for Prisma)
RUN apk add --no-cache openssl libc6-compat && \
    rm -rf /var/cache/apk/*

# Set working directory
WORKDIR /app

# ============================================
# Stage 2: Build application
# ============================================
FROM base AS builder

WORKDIR /app

# Build argument for environment
ARG BUILD_ENV=staging

# Copy package files
COPY package.json package-lock.json ./

# Copy Prisma schema BEFORE npm ci (postinstall script needs it)
COPY prisma ./prisma/

# Install ALL dependencies (including devDependencies for build)
# postinstall script will run prisma generate automatically
# Use BuildKit cache mount for faster rebuilds (requires DOCKER_BUILDKIT=1)
RUN --mount=type=cache,target=/root/.npm \
    npm ci --prefer-offline --no-audit && \
    npm cache clean --force

# Note: Prisma Client is already generated by postinstall script
# But we run it again to ensure it's up to date
RUN npx prisma generate

# Copy source code
COPY . .

# Ensure public folder exists (create if it doesn't)
RUN mkdir -p /app/public || true

# Verify Prisma schema exists
RUN test -f /app/prisma/schema.prisma || \
    (echo "ERROR: Prisma schema not found!" && exit 1)

# Build application with environment-specific config
# Note: .env.${BUILD_ENV} should be available at build time
RUN npm run build:${BUILD_ENV} || \
    (echo "Build failed for environment: ${BUILD_ENV}" && \
     echo "Available .env files:" && \
     ls -la .env* 2>/dev/null || echo "No .env files found" && \
     exit 1)

# ============================================
# Stage 3: Production runtime
# ============================================
FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy standalone output from builder (minimal production bundle)
# Next.js standalone includes: server.js, node_modules (production only), and .next/ folder
# Note: .next/static and public/ are NOT included in standalone by default, so copy them separately
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static files (required - standalone doesn't include them by default)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy public folder (required - standalone doesn't include it by default)
# We ensured public exists in builder stage, so this should always work
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Copy Prisma schema (required for runtime migrations or schema access)
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma

# Verify Prisma schema exists in final image
RUN test -f ./prisma/schema.prisma || \
    (echo "ERROR: Prisma schema.prisma not found in final image!" && \
     ls -la ./prisma/ && exit 1)

# Note: Prisma Client is already included in standalone's node_modules
# Standalone output automatically includes all production dependencies

# Set correct permissions (already set by --chown, but ensure recursively)
RUN chown -R nextjs:nodejs /app

# Add labels for better image management
LABEL org.opencontainers.image.title="Dropfast"
LABEL org.opencontainers.image.description="Dropfast - E-commerce Platform"
LABEL org.opencontainers.image.vendor="Dropfast"

# Switch to non-root user
USER nextjs

# Expose port
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Health check (check root endpoint)
HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/', (r) => {process.exit(r.statusCode < 500 ? 0 : 1)})"

# Override base image entrypoint
ENTRYPOINT []
# Write STRIPE_PUBLISHABLE_KEY to file (so API can read it), then start Node (no external script file needed)
CMD ["sh", "-c", "if [ -n \"$STRIPE_PUBLISHABLE_KEY\" ]; then echo -n \"$STRIPE_PUBLISHABLE_KEY\" > /app/.stripe-publishable-key; echo -n \"$STRIPE_PUBLISHABLE_KEY\" > /app/.next/.stripe-publishable-key 2>/dev/null; fi; exec node server.js"]
